robots.txt

chore: add robots.txt

---

.hlxignore

chore: add .hlxignore

---

package-lock.json
package.json

- https://package-name--helix-website--adobe.hlx3.page/

chore: update package name

---

blocks/sidekick/__tests__/generator.json
blocks/sidekick/__tests__/generator.mock.html
blocks/sidekick/__tests__/generator.mock.json
blocks/sidekick/__tests__/generator.test.js
blocks/sidekick/generator.css
blocks/sidekick/generator.js

- switch to spreadsheet based form
- update URL when user clicks submit for direct sharing
- move all text to gdrive for easier localization
https://sk-gen-form--helix-website--adobe.hlx3.page/tools/sidekick/

feat(sidekick-generator): spreadsheet based form

---

blocks/accordion/accordion.css
blocks/accordion/accordion.js
scripts/scripts.js

A sample block (accordion) for block documentation...
https://blocks--helix-website--adobe.hlx3.page/docs/understanding-blocks

Add accordion sample

---

helix-query.yaml

feat: add helix-query.yaml

---

scripts/scripts.js
tests/scripts/scripts.test.js

- make internal links relative
- open external links in a new window
https://link-handling--helix-website--adobe.hlx3.page/

feat: improve link handling

---

blocks/faq/faq.css
blocks/faq/faq.js
scripts/scripts.js

https://faq--helix-website--adobe.hlx3.page/docs/faq#3
vs. 
https://main--helix-website--adobe.hlx3.page/docs/faq#3

feat: faq block

---

blocks/columns/columns.css

https://two-columns--helix-website--adobe.hlx3.page/docs/sidekick-extension
vs
https://main--helix-website--adobe.hlx3.page/docs/sidekick-extension

feat: two column layout

---

head.html
scripts/scripts.js

Resolves: GH-68
https://GH-68_favicon_fix--helix-website--adobe.hlx3.page/

Fix favicon

---

blocks/sidekick-generator/sidekick-generator.js
img/chrome-web-store.svg
styles/styles.css

Fix #72 
- https://issue-72--helix-website--adobe.hlx3.page/tools/sidekick/

feat: let extension instrument generator page

---

blocks/footnotes/footnotes.css
blocks/footnotes/footnotes.js

https://main--helix-website--adobe.hlx3.page/docs/indexing-reference
vs
https://footnotes--helix-website--adobe.hlx3.page/docs/indexing-reference

feat: simple footnotes block

---

blocks/sidekick-generator/sidekick-generator.js

Fix #72 
- https://issue-72--helix-website--adobe.hlx3.page/

chore: set global flag when block is ready

---

blocks/sidekick-generator/sidekick-generator.js

Remove useless global variable again.
- https://issue-72--helix-website--adobe.hlx3.page/

chore: revert

---

blocks/cards/cards.css
blocks/cards/cards.js
blocks/columns/columns.css
blocks/columns/columns.js
blocks/faq/faq.js
scripts/scripts.js
styles/styles.css
tests/scripts/body.html
tests/scripts/scripts.test.js

https://styling-update--helix-website--adobe.hlx.live/home
vs.
https://main--helix-website--adobe.hlx.live/home

feat: styling update

---

blocks/form/form.css
styles/styles.css

Sample form spec
https://docs.google.com/spreadsheets/d/1JryiDBmOfuBvKgNo0BTuQFEjM94vPxy0Ad37GGgfzgE/edit#gid=0
Rendered form
https://submission--helix-website--adobe.hlx3.page/drafts/jnova/sc-qualform

fix: form styling updates

---

styles/styles.css

Test URL: https://table-styling--helix-website--adobe.hlx.page/docs/setup-byo-cdn-push-invalidation

chore: table styling

---

blocks/footer/footer.css
blocks/footer/footer.js
scripts/scripts.js
styles/styles.css

https://main--helix-website--adobe.hlx3.page/home
vs
https://footer--helix-website--adobe.hlx3.page/home

feat: footer

---

scripts/scripts.js

test url:
- https://avoid-shadow-dom--helix-website--adobe.hlx.page/
- https://avoid-shadow-dom--helix-website--adobe.hlx.page/developer

fix: avoid shadow dom and create data-url svg image

---

blocks/video/video.css
blocks/video/video.js

https://main--helix-website--adobe.hlx.page/developer/tutorial
vs.
https://video--helix-website--adobe.hlx.page/developer/tutorial

feat: simple video block

---

blocks/table/table.css
blocks/table/table.js

URL for testing:
- https://table-blocks--helix-website--adobe.hlx.page/developer/indexing

feat: add table block

---

blocks/form/form.js

add code to pre-fill the registration form from the query params.
before: https://main--helix-website--adobe.hlx.live/tools/bot/register
after: https://populate-registration-form--helix-website--adobe.hlx.live/tools/bot/register

feat: fill registration form

---

scripts/scripts.js
tests/scripts/body.html

https://mobile-breakpoint--helix-website--adobe.hlx.page/home
vs
https://main--helix-website--adobe.hlx.page/home

chore: shift mobile breakpoint from 400px to 600px

---

scripts/scripts.js
styles/styles.css

https://main--helix-website--adobe.hlx.page/home#but-how-fast
https://main--helix-website--adobe.hlx.page/docs/sidekick
vs
https://anchor-docs-only--helix-website--adobe.hlx.page/home#but-how-fast
https://anchor-docs-only--helix-website--adobe.hlx.page/docs/sidekick

feat: copy anchor links on docs page headings

---

blocks/faq/faq.css
blocks/faq/faq.js
scripts/scripts.js

https://www.hlx.live/docs/faq#franklin-and-helix
vs.
https://faq-anchors--helix-website--adobe.hlx.page/docs/faq#franklin-and-helix

feat: faq anchor links

---

scripts/scripts.js

see https://fix-cwv--helix-website--adobe.hlx.live/?rum=on

fix(rum): measure cwv in delayed

---

blocks/sidekick-generator/sidekick-generator.js
tests/blocks/sidekick-generator/sidekick-generator.test.js

Due to the anchor linking of heading elements, the logic was selecting that link and tying the action there instead of the submit button.
I also made url parsing logic support hlx.live and hlx.page urls while I was in there
See: #209 
a user sent me a screenshot of the previous experience and was having trouble getting the project added to their sidekick. the user is non technical, and was putting in the hlx.page preview url, so it made sense to me to add support for those as well.
unit tests
https://sk-gen-fixes-new--helix-website--shsteimer.hlx.page/tools/sidekick/

change submit button selector to get the right button

---

blocks/z-pattern/README.md
blocks/z-pattern/z-pattern.css

Block style changes/additional classes to accommodate the redesign UX of this block. 
Test URLs:
- Before: https://main--helix-website--adobe.hlx.page/drafts/redesign/blocks/z-pattern
- After: https://redesign-z-pattern--helix-website--adobe.hlx.page/drafts/redesign/blocks/z-pattern
Documentation:
- [Readme](https://github.com/adobe/helix-website/tree/redesign/z-pattern/blocks/z-pattern)

[#224] z pattern block redesign ux

---

blocks/form/checkbox-checked.svg
blocks/form/form.css
blocks/form/form.js
styles/styles.css

Two new pages were created with a "contact" template. 
- /contact 
- /thank-you 
Form block was modified to match redesign. 
Note - when testing the form it may take a couple minutes for it to display in the google sheet.
A new form/google sheet was created [here](https://docs.google.com/spreadsheets/d/1f1JyuXqAcuWcvSpdmT09-YYmgoMbfN-YETF2w8seWGk/edit#gid=811418432) 
Test URLs (contact): 
Before: https://website-redesign--helix-website--adobe.hlx.page/drafts/redesign/contact
After: https://redesign-form--helix-website--adobe.hlx.page/drafts/redesign/contact
Test URLs (thank you): 
Before: https://website-redesign--helix-website--adobe.hlx.page/drafts/redesign/thank-you
After: https://redesign-form--helix-website--adobe.hlx.page/drafts/redesign/thank-you

Contact/Thank You Pages (demo form)

---

blocks/card-list/card-list.js

Before: https://main--helix-website--adobe.hlx.page/drafts/amol/block-collection
After: https://main--helix-website--amol-anand.hlx.page/drafts/amol/block-collection

Switching to github profile instead of name, company etc..

---

scripts/scripts.js

this will also fix the bug with RUM data collection due to a missing web-vitals.js file
preview: https://rum-refresh--helix-website--adobe.hlx.live/?rum=on

fix(rum): re-align with helix-project-boilerplate

---

blocks/footer/footer.js
blocks/header/header.css

Adding workaround to support hlx.live link for support 
Before: https://website-redesign--helix-website--adobe.hlx.page/drafts/redesign/new-home
After: https://redesign-migration-qa--helix-website--adobe.hlx.page/drafts/redesign/new-home

[#0] footer link temp fix for chat/support

---

blocks/marquee/marquee.css
blocks/marquee/marquee.js
blocks/tabs/tabs.css

Had to update the tabs/marquee blocks to adjust for the content we are receiving. 
Test URLs 
Before: https://website-redesign--helix-website--adobe.hlx.page/new-home
After: https://redesign-testimonial-update--helix-website--adobe.hlx.page/new-home

[#0] Updates to tabs/marquee for testimonial data

---

blocks/z-pattern/z-pattern.js
scripts/scripts.js
styles/styles.css

see 
- https://trieloff-patch-1--helix-website--adobe.hlx.live/home
Just a quick fix attempt to tweak the LCP

fix(lcp): add only relevant blocks to LCP_BLOCKS

---

styles/styles.css

https://bumper-new--helix-website--adobe.hlx.page/

chore: bumper

---

blocks/columns/columns.css

Related to issue #330, our creative team has reviewed the changes and is aligned with the new updates to the colors.
Test URLs: 
Before: https://main--helix-website--adobe.hlx.page/home
After:  https://nicole-patch-redesign--helix-website--adobe.hlx.page/home

fix: Adjustment for color contrast updates

---

blocks/logo-wall/logo-wall.js

this adds support for SVG logos in the logo wall, you can check it out in the partner section
of https://partner-svg--helix-website--adobe.hlx.page/home

feat(logo-wall): support SVG logos

---

blocks/header/header.js
blocks/z-pattern/z-pattern.js

https://www.hlx.live/home
vs. 
https://a11y-fixes--helix-website--adobe.hlx.live/home

chore: a11y fixes

---

blocks/footer/footer.css
scripts/scripts.js
styles/styles.css

https://main--helix-website--adobe.hlx.live/home
vs.
https://lh-tweaks--helix-website--adobe.hlx.live/home
https://lh-tweaks--helix-website--adobe.hlx.live/docs/
https://lh-tweaks--helix-website--adobe.hlx.live/developer/tutorial

chore: breadcrumb refactor

---

scripts/delayed.js

Soft preload the softnav: only trigger a preload if the mouse is approaching the link.
Test page: https://softnav-soft-preloading--helix-website--adobe.hlx.live/docs/bulk-metadata

feat: soft preloading - only when mouse approaching the link

---

blocks/side-navigation/side-navigation.css
scripts/scripts.js
styles/styles.css

Before:
- https://main--helix-website--adobe.hlx.live/docs/bulk-metadata
After: 
- https://mobile-cls--helix-website--adobe.hlx.live/docs/bulk-metadata

fix: address mobile CLS

---

scripts/scripts.js

Test page: https://soft-nav-history--helix-website--adobe.hlx.live/docs/placeholders

fix: softnav does not support back browser button

---

scripts/scripts.js

See https://svg--helix-website--adobe.hlx.page/docs/architecture

feat(scripts): allow svg in default content

---

scripts/scripts.js

see https://svg-fix-fix--helix-website--adobe.hlx.live/home
and https://svg-fix-fix--helix-website--adobe.hlx.live/docs/architecture

fix(scripts): do not apply svgification to blocks, only to default content

---

blocks/columns/columns.js
plugins/time-decorator.js
scripts/scripts.js

Check out https://pretty-timestamps--helix-website--adobe.hlx.page/community and scroll down to "Upcoming Community Events"
You should see that the dates
- show the proper day of week
- are shown in your current timezone
- show other important timezones on hover
- have an ICS download link

Pretty Timestamps for Community Page

---

blocks/faq/faq.css

https://faq-scrolling--helix-website--adobe.hlx.live/docs/faq#ssg
vs.
https://main--helix-website--adobe.hlx.live/docs/faq#ssg

chore: faq scroll margin

---

tools/sidekick/config.json

https://remove-sidekick-config--helix-website--adobe.aem.page/home

chore: delete tools/sidekick/config.json

---

.github/workflows/test.yml

node 20 upgrade and align ci config with other repos

chore: modernize ci

---

blocks/form/form.js

Use new Helix 5 forms endpoint
- https://forms-fix--helix-website--adobe.aem.live/developer/block-party/submission

fix: use new forms endpoint

---

blocks/deprecation/deprecation.css
blocks/deprecation/deprecation.js
scripts/scripts.js

Adding deprecation banner:
Before: https://main--helix-website--adobe.aem.page/developer/forms
After: https://deprecation-banner--helix-website--adobe.aem.page/developer/forms

feat: deprecation banner

---

blocks/labs/labs.js

See https://custom-labs--helix-website--adobe.aem.page/docs/generate-variations
- feat(labs): allow custom labs headers
- fix(labs): better brand new styling

Custom Labs titles

---

tools/rum/rum-slicer.css
tools/rum/slicer.js

adding yearly view:
https://rum-yearly--helix-website--adobe.aem.page/tools/rum/explorer.html
and a couple of other fixes...

[rum-explorer] enable yearly view

---

tools/rum/cruncher.js
tools/rum/cwvtimeline.js
tools/rum/loader.js
tools/rum/rum-slicer.css
tools/rum/slicer.js
tools/rum/utils.js

This is on top of your `yearly` PR (to avoid merge conflicts) and is a first attempt at
splitting the code up to make it a bit easier to handle
- chore: add yearly view
- chore: remove footer
- chore: main height fix
- refactor(rum-explorer): break data fetching into separate file
- refactor(rum-explorer): move utils and some of the data crunching into a separate file
- refactor(rum-explorer): move (some parts of) cwv timeline chart into separate class

RUM Explorer: initial refactoring

---

blocks/releases/releases.js

**Select all**
**Select none**
**Select some**
- Before: https://main--helix-website--adobe.aem.page/docs/release-history
- After: https://select-all-releases--helix-website--adobe.aem.page/docs/release-history

chore(releases): select/deselect all

---

blocks/author-box/author-box.js
blocks/publication-time/publication-time.js
styles/styles.css
tools/rum/cwvtimeline.js
tools/rum/slicer.js

https://lint--helix-website--adobe.aem.page/home

chore: lint

---

tools/rum/facetsidebar.js
tools/rum/slicer.js

https://rum-cwv-titles--helix-website--adobe.aem.page/tools/rum/explorer.html?domain=emigrationbrewing.com&view=month&domainkey=

chore: add labels to cwv in facets

---

tools/rum/facetsidebar.js
tools/rum/rum-slicer.css

fixing copy/paste export...
https://rum-explorer-copy-paste-fix--helix-website--adobe.aem.page/tools/rum/explorer.html

chore: fix copy/paste to spreadsheet

---

tools/rum/explorer.html
tools/rum/flow.html
tools/rum/list.html
tools/rum/share.html

fix: typo in spreadsheet

---

blocks/columns/columns.css
blocks/columns/columns.js

Before: https://main--helix-website--adobe.aem.page/docs/setup-customer-sharepoint#sign-in-in-the-registration-portal
After: https://fullscreen-images--helix-website--adobe.aem.page/docs/setup-customer-sharepoint#sign-in-in-the-registration-portal

feat(columns): fullscreen images

---

tools/rum/elements/list-facet.js
tools/rum/rum-slicer.css

Some people have lots of values they want to filter https://adobe-dx-support.slack.com/archives/C06AGQKFDAL/p1717622030266739 so I've built the ability to paste values into the filter.
Still needs a pure CSS paste icon.

feat(list-facet): allow pasting filter values from the clipboard

---

tools/rum/elements/list-facet.js
tools/rum/rum-slicer.css
tools/rum/single.html
tools/rum/slicer.js

This reverts commit 375948c3460c50ff0042e27159858ba3bb984ecd.

Single Page Mode

---

scripts/lib-franklin.js

chore: remove useless sessionstorage usage

---

tools/rum/charts/sankey.js

some people say you can't trust them

fix(sankey): remove blind click

---

tools/rum/cruncher.js

Changed the facet lookup algorithm from O(NxM) to O(1) by trading space. 
For some data it can be from
to

fix(rum-explorer): speed up histogram facets

---

tools/oversight/rum-slicer.css

- **fix(oversight): remove lines from thumbnail facet**
- **fix(oversight): more and all links in facets should be next to each other**

Oversight style tweaks

---

tools/oversight/elements/thumbnail-facet.js
tools/oversight/explorer.html
tools/oversight/rum-slicer.css

see https://oversight-lcp-facets--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=www.aem.live&filter=&view=month&checkpoint=cwv-lcp&conversion.checkpoint=click

feat(oversight): show LCP facet

---

scripts/lib-franklin.js

With Helix5, the RUM collection happens on the same host.
Test URL: https://rum-v5--helix-website--adobe.aem.live/?rum=on

feat: use same host for RUM collection

---

tools/oversight/rum-slicer.css
tools/rum/rum-slicer.css

Sorry @trieloff, I like the gradient but the input field is not usable with long host names...

fix: remove gradient

---

tools/oversight/test/acquisition.test.js

unit tests for the acquisition classification logic

test(acquisition): unit tests

---

tools/oversight/charts/barchart.js
tools/oversight/charts/piechart.js
tools/oversight/charts/sankey.js
tools/oversight/charts/skyline.js
tools/oversight/elements/facetsidebar.js
tools/oversight/slicer.js
tools/oversight/utils.js

Same as #612 for Oversight.
Test: https://oversight-no-focus--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=www.adobe.com&filter=&view=week&domainkey=incognito

feat(rum-oversight): remove unused focus

---

blocks/sidekick-generator/sidekick-generator.js
tests/blocks/sidekick-generator/sidekick-generator.test.js

https://sk-share-title--helix-website--adobe.aem.page/tools/sidekick/?giturl=https%3A%2F%2Fgithub.com%2Fadobecom%2Fblog%2Ftree%2Fmain&project=Blog
vs
https://main--helix-website--adobe.aem.page/tools/sidekick/?giturl=https%3A%2F%2Fgithub.com%2Fadobecom%2Fblog%2Ftree%2Fmain&project=Blog

feat(sidekick-generator): show project in document title

---

scripts/scripts.js
tools/rum/rum-slicer.css

https://main--helix-website--adobe.aem.page/
vs.

chore: test google indexing

---

head.html
scripts/indexing-test.js
scripts/scripts.js

Index test

---

head.html
scripts/indexing-test.js

chore: change counter

---

head.html
scripts/indexing-test.js

chore: meta test

---

blocks/card-list/card-list.css
blocks/card-list/card-list.js
blocks/cards/cards.js

Modifies the Cards List block used by block party (and best I can tell, only by block party) to do 2 things:
1. sort by highlighted first, then reverse chronological (newest first)
2. add filtering by the category field
as block party has grown, harder to find things. this makes that easier with minimal impact anywhere else
https://card-list-block-party--helix-website--adobe.aem.page/developer/block-party/
https://card-list-block-party--helix-website--adobe.aem.page/docs/ (uses same block but a different variant)

feat: add filtering to card list used for block party. change sort to use highlight and then sort newest first

---

scripts/scripts.js

chore: after last modified fixes

---

blocks/labs/labs.css
blocks/labs/labs.js

see https://labs-links--helix-website--adobe.aem.page/?experiment=short-home%2Fcontrol

Allow Links in Labs

---

tools/sidekick/app.js

PSI check: https://eol-sidekick-bookmarklet--helix-website--adobe.aem.page/
Test bookmarklet:
```
javascript:/* ** AEM Sidekick Bookmarklet ** */(() => %7Bconst c=%7B"owner":"foo","repo":"bar","ref":"main"%7D;const s=document.createElement('script');s.id='hlx-sk-app';s.src='https://eol-sidekick-bookmarklet--helix-website--adobe.aem.page/tools/sidekick/app.js';s.dataset.config=JSON.stringify(c);if(document.getElementById('hlx-sk-app'))%7Bdocument.getElementById('hlx-sk-app').replaceWith(s);%7D else %7Bdocument.head.append(s);%7D%7D)();
```

chore(sidekick):  bookmarklet end of life

---

blocks/releases/releases.css
blocks/releases/releases.js

Before: https://main--helix-website--adobe.aem.page/docs/release-history
After: https://config-releases--helix-website--adobe.aem.page/docs/release-history

feat: add config service releases

---

tools/sidekick/config.schema.json

Update sidekick schema with recently added features badge & content source support
https://github.com/adobe/helix-sidekick-extension/issues/786

chore: update sidekick schema with badge & content source support

---

tools/oversight/charts/sankey.js
tools/oversight/explorer.html
tools/oversight/flow.html
tools/oversight/list.html
tools/oversight/package.json
tools/oversight/share.html
tools/oversight/single.html
tools/rum/explorer.html
tools/rum/package.json

This PR includes transfer of `reclassifyEnter` function from `rum-distiller` to `sankey.js`
This also includes bumping `rum-distiller` version to `1.10.0` in all required files
#684 
Moving the function across since it's usage is limited to `sankey.js`
Tested on URLs below:
https://issue-684--helix-website--adobe.aem.page/tools/oversight/flow.html?domain=emigrationbrewing.com&filter=&view=month&=performance&domainkey=open&conversion.checkpoint=click&drilldown=checkpoint
Sankey diagram appears as expected
Tested on:
https://main--helix-website--adobe.aem.page/tools/oversight/flow.html?domain=emigrationbrewing.com&filter=&view=month&=performance&domainkey=open&conversion.checkpoint=click&drilldown=checkpoint
vs
https://issue-684--helix-website--adobe.aem.page/tools/oversight/flow.html?domain …

Transfer reclassifyEnter function & bump rum-distiller version to 1.10.0

---

tools/oversight/explorer.html
tools/oversight/flow.html
tools/oversight/list.html
tools/oversight/package.json
tools/oversight/share.html
tools/oversight/single.html
tools/rum/explorer.html
tools/rum/package.json

Bumps the `rum-distiller` version to `1.11.0`

fix(deps): bump rum-distiller to v1.11.0

---

tools/oversight/explorer.html
tools/oversight/flow.html
tools/oversight/list.html
tools/oversight/package.json
tools/oversight/share.html
tools/oversight/single.html
tools/rum/explorer.html
tools/rum/package.json

This PR bumps distiller version to 1.11.1
Explorer up again at https://distiller-v1-11-1--helix-website--adobe.aem.live/tools/rum/explorer.html

fix(deps): bump distiller to v1.11.1

---

tools/oversight/elements/list-facet.js

PR to add title for facet clipboard in explorer UI
For better user experience, hovering over icon displays the usage
Tested on Explorer UI

chore: add title for facet clipboard (RUM)

---

package.json
tools/oversight/explorer.html
tools/oversight/flow.html
tools/oversight/list.html
tools/oversight/package.json
tools/oversight/share.html
tools/oversight/single.html
tools/rum/explorer.html
tools/rum/package.json

This PR upgrades distiller version to `1.12.0`

fix(deps): bump distiller to v1.12.0

---

blocks/releases/releases.css
blocks/releases/releases.js

Before:
- https://main--helix-website--adobe.aem.page/docs/release-history
- https://aem-sidekick-releases--helix-website--adobe.aem.page/docs/release-history

chore(releases): add aem-sidekick

---

blocks/deprecation/deprecation.css
blocks/deprecation/deprecation.js

Before: https://main--helix-website--adobe.aem.page/developer/upgrade
After: https://deprecation-styling--helix-website--adobe.aem.page/developer/upgrade

chore(deprecation): custom title and styling

---

.renovaterc.json

This PR adds renovate config to update distiller version in explorer and oversight
#701 
Currently, version upgrade has to be done manually, this change will save manual effort.
- [] Bug fix (non-breaking change which fixes an issue)

feat: renovate config to update distiller version

---

package-lock.json
package.json
tools/oversight/package-lock.json
tools/oversight/package.json
tools/rum/package-lock.json
tools/rum/package.json

Reverts adobe/helix-website#707

Revert "chore(deps): update dependency @adobe/rum-distiller to v1.13.1"

---

.renovaterc.json
.stylelintrc.json
blocks/author-box/author-box.css
blocks/availability/availability.css
blocks/card-list/card-list.css
blocks/cards/cards.css
blocks/columns/columns.css
blocks/copy/copy.css
blocks/feature-list/feature-list.css
blocks/feed/feed.css
blocks/footer/footer.css
blocks/form/form.css
blocks/get-started/get-started.css
blocks/header/header.css
blocks/hero/hero.css
blocks/logo-wall/logo-wall.css
blocks/marquee/marquee.css
blocks/pagination/pagination.css
blocks/roi-calculator/roi-calculator.css
blocks/side-navigation/side-navigation.css
blocks/svg-doctor/svg-doctor.css
blocks/tabs/tabs.css
blocks/testimonials/testimonials.css
blocks/z-pattern/z-pattern.css
package-lock.json
package.json
styles/styles.css

stylelint upgrade to v16 and align all new styles requirements.
Test: https://stylelint-upgrade--helix-website--adobe.aem.live/

chore: upgrade to stylelint 16

---

plugins/experimentation/package-lock.json
plugins/experimentation/package.json
plugins/experimentation/src/index.js

Various linting dep upgrade.
@ramboz I wonder why we have never seen that `plainPath` is not defined in the `catch`

chore(experimentation): upgrade linting

---

blocks/feed/feed.css
blocks/feed/feed.js
scripts/scripts.js
styles/styles.css

This PR introduces Blog List Page for listing the blog posts on AEM live documentation
#735 
Currently there isn't any parent or home page for listing blogs.
The blog listing page will be a central place to link all blog posts present on the aem.live website.
https://main--helix-website--adobe.aem.page/drafts/asthabharga/blog-test
vs
https://issue-733--helix-website--adobe.aem.page/drafts/asthabharga/blog-test

feat: Blog List Page Design

---

blocks/feed/feed.css
blocks/feed/feed.js

This PR handles heading order for the blog list home page and it's style
#735 
This is related to and continuation of changes in issue #735 
https://main--helix-website--adobe.aem.page/blog
vs
https://blog-list-page--helix-website--adobe.aem.page/blog
- [] New feature (non-breaking change which adds functionality)

Updated layout for blog list home page

---

tools/oversight/elements/incognito-checkbox.js
tools/oversight/elements/url-selector.js
tools/oversight/loader.js
tools/oversight/slicer.js
tools/rum/admin/store.js
tools/rum/elements/incognito-checkbox.js
tools/rum/elements/url-selector.js
tools/rum/loader.js
tools/rum/slicer.js

https://new-domain--helix-website--adobe.aem.live/tools/rum/explorer.html
ref: https://github.com/adobe/helix-rum-bundler/pull/275

fix(rum): use new bundles domain

---

blocks/releases/releases.css
blocks/releases/releases.js

see https://dangerous-releases--helix-website--adobe.aem.page/docs/release-history

fix(releases): display infrastructure changes

---

scripts/lib-franklin.js

depends on #760 
see https://rum-enhancer-beta--helix-website--adobe.aem.page/?rum=on

rum enhancer beta

---

scripts/lib-franklin.js

try https://bump-rum-js--helix-website--adobe.aem.page/?rum=on

fix(lib-franklin): bump rum-js version to 2.10.0

---

blocks/author-box/author-box.css

Fixes the appearance of profile pics which was impacted by long author-blurb
https://main--helix-website--adobe.aem.page/blog/calendar-implementation
vs
https://author-box-images--helix-website--adobe.aem.page/blog/calendar-implementation

fix: author-box profile pics

---

404.html
head.html

Tryout CSP with nonce on https://www.aem.live .
Depends on https://github.com/adobe/helix-html-pipeline/pull/773 .
Mitigate possible XSS.
More context in: https://github.com/adobe/helix-html-pipeline/pull/773 .
Using:
https://cspnonce--helix-website--adobe.aem.page/
https://cspnonce--helix-website--adobe.hlx.page/docs/
https://cspnonce--helix-website--adobe.hlx.page/notfound

feat: Enable CSP with nonce

---

404.html
head.html

Reverts adobe/helix-website#776

Revert "feat: Enable CSP with nonce"

---

.github/track-publishes.yml
.github/workflows/log-publish.yml

We'll probably need to tweak this in main. It does not cover bulk publishes yet and there isn't any pagination of the admin api results

ci(github): refactor workflow to use polling of AEM Live Admin API to invoke workflow dispatch events

---

tools/oversight/cwvperf.html
tools/oversight/explorer.html
tools/oversight/flow.html
tools/oversight/list.html
tools/oversight/share.html
tools/oversight/single.html

see https://bump-chartjs--helix-website--adobe.aem.live/tools/oversight/share.html?domain=emigrationbrewing.com&view=month&domainkey=open&drilldown=userAgent

chore(deps): upgrade Chart.js to version 4.4.8 across RUM tools

---

blocks/side-navigation/side-navigation.css

Before: https://main--helix-website--adobe.aem.page/docs/faq
After: https://search-fixes--helix-website--adobe.aem.page/docs/faq

fix: fixing search results display

---

blocks/table/table.js

https://main--helix-website--adobe.aem.page/docs/sidekick-errors
vs.
https://table-update--helix-website--adobe.aem.page/docs/sidekick-errors
...backwards compatibility
https://main--helix-website--adobe.aem.page/docs/byo-cdn-akamai-setup
vs. 
https://table-update--helix-website--adobe.aem.page/docs/byo-cdn-akamai-setup

Table update

---

styles/styles.css

see https://block-color--helix-website--adobe.aem.page/developer/ue-tutorial

fix(styles): do not override text color in blocks

---

blocks/feed/feed.css
blocks/feed/feed.js

This PR adds a card layout for adding links to partner blogs which will feature on AEM.live blog.
#809 
https://main--helix-website--adobe.aem.page/drafts/asthabharga/blog
vs
https://partner-blog--helix-website--adobe.aem.page/drafts/asthabharga/blog

feat: support for partner blogs on AEM.live blog

---

blocks/author-box/author-box.css
blocks/author-box/author-box.js

This PR fixes author-box layout for more than two authors. Currently the layout looks odd.
#816 
Consistency of design even for greater number of authors for a blog
- 3 authors:
https://main--helix-website--adobe.aem.page/blog/organizing-source-code-ensemble
vs
https://author-box-fix--helix-website--adobe.aem.page/blog/organizing-source-code-ensemble
- 4 authors:
https://main--helix-website--adobe.aem.page/drafts/asthabharga/blog-calendar-test
vs
https://author-box-fix--helix-website--adobe.aem.page/drafts/asthabharga/blog-calendar-test
- 2 authors (unchanged)
https://main--helix-website--adobe.aem.live/blog/calendar-implementation
vs
https://author-box-fix--helix-website--adobe.aem.live/blog/calendar-implementation
- 1 author (unchanged) …

[author-box] update author-box design for more than two authors

---

llms.txt

Created `llms.txt` from side navigation md.
- https://llmstxt--helix-website--adobe.aem.page/

chore: add llms.txt

---

blocks/card-list/card-list.js
blocks/embed/embed.css

before: https://main--helix-website--adobe.aem.page/drafts/amol/block-party-index
after: https://block-party-update--helix-website--adobe.aem.page/drafts/amol/block-party-index
before: https://main--helix-website--adobe.aem.page/drafts/amol/submission-embed
after: https://block-party-update--helix-website--adobe.aem.page/drafts/amol/submission-embed
Pointing to the new curated list that includes the old entries and any new entries from the updated google form. Once this goes in, we need to make two content updates:
1. Change the content of the block party page to point to https://www.aem.live/developer/block-party/block-party.json?sheet=curated-list-new 
2. Change the content of the submission page form to link to the new google form as shown here: …

fix: for the new block party form update

---

tools/oversight/explorer.html

showing raw utm source and target

---

blocks/event-banner/event-banner.css
blocks/event-banner/event-banner.js
blocks/event-cta/event-cta.css
blocks/event-cta/event-cta.js

- event-banner: Fix desktop height to 472px for proper 1200x472 proportions
- event-banner: Improve mobile background scaling and content positioning
- event-banner: Increase subtitle font size to 22px on desktop
- event-cta: Optimize mobile typography (18px tablet, 16px mobile)
- event-cta: Reduce bottom padding for better vertical spacing
Issue #875 
2 issues - Mobile users who want to view the site would get a lousy visual experience on entry - poor alignment of text. And the UTM codes would not be transferred to Bevy if a customer clicked on the register at the bottom of the page.
Now breaking out the CTA from the event-banner we can use the same UTM friendly code in the register button at the top AND the bottom of the page. Awesome!
Ran CSS Lint and ESLint on JS. Both found issues …

Fix event-banner and event-cta mobile/desktop styling

---

tools/oversight/cwvperf.html
tools/oversight/explorer.html
tools/oversight/flow.html
tools/oversight/list.html
tools/oversight/share.html
tools/oversight/single.html

fix: Update page title from RUM to Operational Telemetry

---

blocks/ue-trial/ue-trial.css
blocks/ue-trial/ue-trial.js

This change will add a sign up form for the Universal Editor trial Program. The sign up form should be part of the universal editor tutorial at https://www.aem.live/developer/ue-tutorial.
fixes: #878 
See issue description in #878 
Test URL: https://ue-trial--helix-website--adobe.aem.live/drafts/pauli/ue-trial

feat: Add trial sign up form for Universal Editor tutorial

---

blocks/event-cta/event-cta.css
blocks/event-cta/event-cta.js

- Move addUTMTracking() call after DOM manipulation to prevent href loss
- Fix NodeList.some() compatibility issue by using Array.from() conversion
- Simplify UTM tracking function by removing unnecessary array collection
- Use direct for...of loop instead of complex forEach chains
- Created a new variant called (multi) that enables multiple buttons to be presented in a horizontal line
Fixes both the functional bug (UTM parameters not forwarding) and the compatibility issue (NodeList.some() not available in all environments).
https://github.com/adobe/helix-website/issues/898
Not customers that land on /developers-live from other locations with UTM codes will pass those nifty codes to the reg site. Groovy.
URL for testing:
- https://fix-utm-tracking-issue--helix-website--adobe.aem.live/deve …

[DevLive] Fix UTM tracking event-cta block

---

blocks/z-pattern/z-pattern.css

Before: https://main--helix-website--adobe.aem.live/community
After: https://z-pattern-fix--helix-website--adobe.aem.live/community

fix: embed size in content-side

---

tools/oversight/charts/sankey.js

see
https://sankey-fix--helix-website--adobe.aem.live/tools/oversight/flow.html?domain=www.aem.live&view=month&domainkey=BRINGYAOWNKEY&drilldown=checkpoint
Signed-off-by: Lars Trieloff <lars@trieloff.net>

fix(sankey): make sankey diagram work for aem.live

---

tools/oversight/explorer.html

Added Form Fill and Form Submit Events in the dashboard
https://form-checkpoints--helix-website--vdua.aem.live/tools/oversight/explorer.html?domain=business.adobe.com&view=month&domainkey=incognito

feat: adding form checkpoints in the dashboard
