blocks/sidekick-generator/sidekick-generator.js, tests/blocks/sidekick-generator/sidekick-generator.test.js
Fix #72 
- use `sidekickGeneratorReady` event (fired by the block) to show bookmarklet container
https://issue-72--helix-website--adobe.hlx3.page/
=> chore: event based container display

tools/sidekick/config.schema.json
With Helix Sidekick extension manifest v3, we will switch to a JSON config. This is the schema that defines the supported properties.
@dylandepass @trieloff: this is my first attempt at defining a JSON schema, so I'd appreciate your feedback!
See:
- https://github.com/adobe/helix-sidekick-extension/issues/103
- https://github.com/adobe/helix-sidekick-extension/blob/mv3/docs/API.md#plugin--object
=> feat(sidekick): config json schema

scripts/scripts.js
Added a little delay (used successfully in CCX as well) to ensure the page is always scrolling to the hash ID.
=> chore: scroll to hash not always working

blocks/video/video.js, tests/blocks/video/video.test.js, tests/utils.js
Example code with a MockIntersectionObserver to control the intersections and call before tests can be run...
Note that is the not the perfection solution. A better approach would be to unit test the `decorateVideoBlock`. But for that, you need to export the function, at least in the testing env (which would be doable with the build tools that we do not want to use).
=> feat: video test with MockIntersectionObserver

scripts/scripts.js
the previous fix would not account for delayed loading of fragments
such as the FAQ block, causing the condition not being met and
the timout never being set.
fixes #111 alternative to #124
Before: https://main--helix-website--adobe.hlx.page/docs/faq#q33
After: https://fragment-identifier-scroll--helix-website--adobe.hlx.page/docs/faq#q33
=> fix(scripts): avoid race condition for `scrollIntoView`

blocks/form/checkbox-checked.svg, blocks/form/form.css, blocks/form/form.js
There is `.form-checkbox-wrapper` styling, but the class is only applied to fields labeled `checkbox`. This change applies the class name based on the type instead of label.
Before: https://main--helix-website--adobe.hlx.page/vip/customer-intake
After: https://form-tweaks--helix-website--adobe.hlx.page/vip/customer-intake
=> fix(form): checkbox styling

scripts/scripts.js
https://main--helix-website--adobe.hlx.page/docs/sidekick
vs
https://rofe-patch-1--helix-website--adobe.hlx.page/docs/sidekick
=> chore: fix anchor links regression

blocks/sidekick-library/sidekick-library.css, blocks/sidekick-library/sidekick-library.js, head.html, scripts/scripts.js
The PR adds the sidekick library block. Customers who use the sidekick library will load the hosted library using this block.
[Demo](https://sidekick-library--helix-website--adobe.hlx.page/tools/sidekick/library?base=https://main--helix-test-content-onedrive--adobe.hlx.page/block-library-tests/library-single-sheet.json)
Couple notes.
* The `crossorigin="use-credentials"` attribute was removed from the script tag importing `scripts.js`. This is required so that the sidekick library can receive responses from requests that return `*` in the `access-control-allow-origin` header. Based on [this thread](https://cq-dev.slack.com/archives/C9KD0TT6G/p1666685656854529) I believe that this is a change that just haven't come across yet from boilerplate. 
* When the sidekick library page renders, it …
=> feat: add sidekick library block

blocks/breadcrumb/README.md, blocks/breadcrumb/breadcrumb.css, scripts/scripts.js
Added a breadcrumb block that can be used on its own - but also gets built by default into documentation pages. Related to #236 
Test URLs (block)
Before: https://website-redesign--helix-website--adobe.hlx.page/drafts/redesign/blocks/breadcrumb
After: https://redesign-breadcrumbs--helix-website--adobe.hlx.page/drafts/redesign/blocks/breadcrumb
[Readme](https://github.com/adobe/helix-website/blob/redesign/breadcrumbs/blocks/breadcrumb/README.md)
=> [#0] Block - Breadcrumb

blocks/breadcrumb/breadcrumb.css, blocks/breadcrumb/breadcrumb.js, blocks/side-navigation/side-navigation.css, blocks/side-navigation/side-navigation.js, styles/styles.css
Updating breadcrumbs to also inject a back button to the main content area that leads back to the documentation page.
Test URLs
Before: https://website-redesign--helix-website--adobe.hlx.page/drafts/redesign/docs/anatomy-of-a-helix-project 
After: https://redesign-doc-detail-page--helix-website--adobe.hlx.page/drafts/redesign/docs/anatomy-of-a-helix-project
=> [#0] Adding back button to documentation pages

blocks/card-list/card-list.css, blocks/card-list/card-list.js
Truncating long descriptions to 25 words and showing the extra on toggle click of description
Before: https://main--helix-website--adobe.hlx.page/drafts/amol/block-collection
After: https://main--helix-website--amol-anand.hlx.page/drafts/amol/block-collection
Look at the block party card list at the bottom of the page to see the difference.
=> handling long descriptions

blocks/hero/README.md, blocks/hero/hero.css, blocks/hero/hero.js, styles/styles.css
Fix for issue:
#298 support cta buttons list in documentation hero
Note:
- need to use with `.multiple-cta` on `hero` block for the button list style
Google Doc:
https://docs.google.com/document/d/197AUaVWYZw-DCzYinzOJn3F5PcncZ0JT5KuvLWR2JVM/edit
Test URLs:
Before: https://website-redesign--helix-website--adobe.hlx.page/drafts/redesign/documentation
After: https://redesign-doc-hero-update--helix-website--adobe.hlx.page/drafts/redesign/documentation
=> Redesign: support cta button list in documentation hero

styles/styles.css
ensure only the first image on the page is decorated as a hero.
Fix #347 
https://fragment-nohero--helix-website--shsteimer.hlx.page/docs/byo-cdn-akamai-setup
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.
=> fix: ensure hero image is the first image in the first content wrapper

blocks/breadcrumb/breadcrumb.css, styles/styles.css
This should prevent the hero taking up so much space that the page headline becomes unreadable.
https://trieloff-patch-1--helix-website--adobe.hlx.page/docs/rum
=> fix(guides): limit hero max size in docs

blocks/testimonials/testimonials.js
Some SVG logos would not load in Firefox. The root cause was an unterminated CSS select expression that Chrome ignored, but Firefox failed with. This fix closes the bracket
See https://svg-fix--helix-website--adobe.hlx.live/home
Kudos to @stefanseifert for reporting the issue
=> fix(testimonials): close bracket in css expression

blocks/breadcrumb/breadcrumb.css, blocks/embed/embed.js, styles/styles.css
Reported Issue:
- 0.247 CLS with 86 mobile lighthouse score reported in this doc detail page
https://pagespeed.web.dev/analysis/https-www-hlx-live-docs-sidekick/rc88p931o4?form_factor=mobile
Updates in current PR:
- update `embed.js` to use intersectionObserver for rendering youtube & gist block
- fixed height in breadcrumb to prevent layout shift
- cleanup unused css
Test Urls:
Before: https://main--helix-website--adobe.hlx.page/docs/sidekick
After: https://redesign-doc-page-perf-fix--helix-website--adobe.hlx.live/docs/sidekick
=> [#329] Performance fix: doc detail page

blocks/video/video.js
https://main--helix-website--adobe.hlx.page/
vs.
https://rum-play--helix-website--adobe.hlx.page/
=> chore: add rum play event

blocks/table/table.css
We found this issue during the support training today :)
See https://table--helix-website--adobe.hlx.live/developer/indexing#setting-up-properties-to-be-added-to-the-index (scroll to the first table)
and compare it to https://main--helix-website--adobe.hlx.live/developer/indexing#setting-up-properties-to-be-added-to-the-index
=> fix(table): don't uppercase the first row if there is a header row

blocks/releases/releases.css, blocks/releases/releases.js
https://release-history--helix-website--adobe.hlx.live/docs/release-history
vs.
https://main--helix-website--adobe.hlx.live/docs/release-history
=> feat: add release history

blocks/releases/releases.js
Adding anchor links to release headings: 
https://main--helix-website--adobe.hlx.live/docs/release-history
vs
https://release-anchors--helix-website--adobe.hlx.live/docs/release-history
=> feat: add anchor links to release headings

blocks/releases/releases.css, blocks/side-navigation/side-navigation-search.js, blocks/side-navigation/side-navigation.js, scripts/scripts.js
https://main--helix-website--adobe.hlx.live/docs/
vs.
https://misc-improvements--helix-website--adobe.hlx.live/docs/
- improved search ranking
- slightly improved user experience navigating away from `/docs/` via sidenav
- css linting
=> chore: search and softnav nits, and linting

helix-sitemap.yaml
https://configless-sitemap--helix-website--adobe.aem.page/home
vs. 
https://main--helix-website--adobe.aem.page/home
=> chore: remove sitemap config

blocks/side-navigation/side-navigation.css, styles/styles.css
When search results are displayed on the docs page with a widescreen, the layout was off balance.
I adjusted the CSS for widescreen display in this situation.
Fix #471 
User experience
CSS change only.
Test URLs:
- Before: https://main--helix-website--adobe.aem.live/docs/?q=font
- After: https://471-docs-widescreen--helix-website--adobe.aem.live/docs/?q=font
=> Widescreen display of Docs with Search Results

scripts/delayed.js, scripts/scripts.js
Use prerender instruction https://developer.chrome.com/docs/web-platform/prerender-pages when mouse approaching a link and remove the softnav, i.e. do a classic navigation while target page has been prerendered.
Before: https://main--helix-website--adobe.aem.page/developer/tutorial
After: https://prerender--helix-website--adobe.aem.page/developer/tutorial
=> feat: remove softnav and use prerender

blocks/publication-time/publication-time.css, blocks/publication-time/publication-time.js, tests/blocks/publication-time/publication-time.mock.html, tests/blocks/publication-time/publication-time.test.js, web-components/relative-time.js
https://main--helix-website--adobe.aem.page/developer/web-components
vs
https://publication-time-block--helix-website--bdelacretaz.hlx.page/developer/web-components
This adds a `publication-time` block for the upcoming Web Components docs page, using the https://github.com/github/relative-time-element component to display time in a friendly way such as "3 days ago", "18 minutes ago" etc.
It replaces #459, using a Web Component that's actually (somewhat) useful for the website as opposed to a completely distinct example, as discussed with @kptdobe 
#457
Besides visual testing, the new code is covered by automated tests.
=> Add publication-time block for the Web Components documentation page

blocks/header/header.css, tools/rum/explorer.html, tools/rum/rum-slicer.css, tools/rum/slicer.js
https://rum-explorer-mobile--helix-website--adobe.aem.live/tools/rum/explorer.html
=> chore: improve mobile view

tools/rum/slicer.js
who'd have thunk: Safari does not support filters on iterators
=> fix(rum-explorer): fix safari

tools/rum/slicer.js
https://www.aem.live/tools/rum/explorer.html?domain=emigrationbrewing.com&filter=&view=year&focus=lcp&domainkey=
vs.
https://rum-explorer-focus--helix-website--adobe.aem.page/tools/rum/explorer.html?domain=emigrationbrewing.com&filter=&view=year&focus=lcp&domainkey=
=> chore: highlight focus if selected from URL query param

tools/rum/facetsidebar.js
Before:
- https://www.aem.live/tools/rum/explorer.html?domain=www.adobe.com&filter=&view=year&checkpoint=click&domainkey=9A3B022A-4C58-4060-A76E-04DD0E70F1D0
- full ui updated in 388ms
After
- https://explorer-tsv--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.adobe.com&filter=&view=year&checkpoint=click&domainkey=9A3B022A-4C58-4060-A76E-04DD0E70F1D0
- full ui updated in 378ms
While gain on rendering speed is minimum, we save a lot of memory not computing some large strings (only needed if someone hits the copy button).
There are certainly ways to not recompute everything, just reading the values... For now, it is ok as is.
=> feat(rum-explorer): isolate tsv computation

tools/rum/facetsidebar.js
Added # of samples to core web vital tooltips to help explain why some facets do not show numbers due to not enough samples.
Discussed in `#rum-explorers`.
=> add more descriptive cwv tooltip

blocks/feed/feed.css, blocks/feed/feed.js, scripts/scripts.js, styles/styles.css
Currently the details of discord events (Recent recordings) are added manually on community page. This PR introduces a new block (Feed block) which dynamically fetches these details from community-feed.json (once the event is complete and its details are published there). 
Fix for #536 
No more manual intervention required to update event/recording details once they are completed. It just requires discord event to be created on calendar and rest of the workflow to update the details is handled.
https://main--helix-website--adobe.aem.page/drafts/asthabharga/community
vs
https://issue-536--helix-website--adobe.aem.page/drafts/asthabharga/community
=> feat: feed block for community feed

tools/rum/elements/facetsidebar.js, tools/rum/rum-slicer.css, tools/rum/slicer.js
form elements (input, select) in rum explorer were using default browser font fallbacks. propose to inherit font styling for form elements.
See https://rum-fonts--helix-website--adobe.aem.page/tools/rum/explorer.html?domainkey=incognito.
Left: Previous.
Right: Suggested.
=> fix: rum form elements inherit font

tools/rum/elements/url-selector.js, tools/rum/explorer.html, tools/rum/flow.html, tools/rum/list.html, tools/rum/rum-slicer.css, tools/rum/share.html, tools/rum/slicer.js
This gets rid of the blocking `diaglog`
- **wip: new url selector custom element**
- **feat(rum-explorer): use input field in custom element instead of dialog for URL entry**
- **fix(rum-explorer): disable url entry if no key in local storage**
=> URL as custom element

tools/rum/elements/link-facet.js, tools/rum/explorer.html, tools/rum/rum-slicer.css
=> feat(link-facet): add option to fall back to favicon, if no og:image can be found

tools/rum/rum-slicer.css
https://rum-thumbnail-facet--helix-website--adobe.aem.page/tools/rum/explorer.html?domain=emigrationbrewing.com&filter=&view=month&checkpoint=viewmedia&domainkey=open&conversion.checkpoint=click
vs. 
https://main--helix-website--adobe.aem.page/tools/rum/explorer.html?domain=emigrationbrewing.com&filter=&view=month&checkpoint=viewmedia&domainkey=open&conversion.checkpoint=click
=> chore: add styling to thumbnail facet

tools/rum/elements/link-facet.js, tools/rum/rum-slicer.css
=> feat(rum-explorer): hide protocol and hostname from link facet if there is not enough space

tools/rum/charts/sankey.js, tools/rum/explorer.html, tools/rum/flow.html
In explorer, we'll use the `paid` checkpoint instead of UTM to detect bought traffic. (see https://adobe.enterprise.slack.com/files/W5BPKRLUA/F077XV2J4JE/screenshot_2024-06-13_at_11.39.02.png)
In the sankey diagram, we use lighter colors for the no content and no interaction nodes, making them visually lighter
Sankey also shows now three ways of entering (consent shown, consent hidden, normal enter). (see https://adobe.enterprise.slack.com/files/W5BPKRLUA/F077S4128QN/screenshot_2024-06-13_at_14.20.41.png)
- **feat(rum-explorer): add `paid` facet instead of `utm` facet**
- **feat(rum-explorer): use `paid` checkpoint in addition to `utm` checkpoint for sankey**
- **fix(sankey): no interaction is white, leading to less washed-out gradients**
- **feat(sankey): show consent/noconsent upon …
=> Better visualization of paid and consent flows

tools/rum/cruncher.js, tools/rum/elements/list-facet.js, tools/rum/rum-slicer.css, tools/rum/test/cruncher.test.js
The current conversion rate display is a bit noisy. With this change,
no conversion rate will be shown for most facets. If the facet has
a significantly different conversion rate from the baseline, then it
will be shown. The greater the significance, the greater the opacity of
the label. This allows you to quickly spot facets (or segments) that
are worthy of attention.
- **feat(rum-explorer): add significance flag to conversion rates display**
- **fix(rum-explorer): better styling for interesting and significant conversion rate differences**
=> Hide Non-Significant Conversion Rate

tools/oversight/charts/skyline.js, tools/oversight/cruncher.js, tools/oversight/elements/number-format.js, tools/oversight/rum-slicer.css
See https://oversight-trends--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=www.aem.live&filter=&view=month&checkpoint=cwv-lcp&conversion.checkpoint=click
Note the little line below some of the key metrics, indicating if the trend shows an improvement over time
=> feat(oversight): add trend indicators when looking at date-range chart

tools/oversight/consent.js, tools/oversight/elements/conversion-tracker.js, tools/oversight/elements/number-format.js, tools/oversight/elements/url-selector.js, tools/oversight/explorer.html, tools/oversight/flow.html, tools/oversight/list.html, tools/oversight/rum-slicer.css, tools/oversight/share.html, tools/oversight/single.html, tools/oversight/slicer.js, tools/oversight/utils.js
Following main changes:
- if no conversion target has been defined, we report "Engagement" instead
- "Engaged" are page views that have a click outside a consent dialog
- Conversions are calculated against visits, engagement against page views
- We detect clicks to common consent vendors and break them out under the `consent` checkpoint
See https://cq-dev.slack.com/archives/C07198KKQ07/p1720645069632019
=> Oversight: don't inflate conversion rates

tools/oversight/acquisition.js, tools/oversight/charts/sankey.js, tools/oversight/elements/number-format.js, tools/oversight/explorer.html, tools/oversight/slicer.js, tools/oversight/utils.js, tools/patches.sh
This creates a sparser (and hopefully more readable) Sankey diagram.
The first column groups acquisition sources into:
- Search
- Social
- Email
- Local
- Display
- (plus internal navigation, reload, etc)
The second column groups the type of traffic acquisition:
- Paid
- Owned
- Earned
The rest stays almost as is, except that nodes for explicit link clicks have been removed
Preview: https://cq-dev.slack.com/archives/C07198KKQ07/p1721072766659269
- **feat(oversight): classify traffic acquisition**
- **fix(oversight): remove special handling of utm parameter**
- **feat(oversight): display traffic sources**
- **fix(oversight): remove drilldown for traffic source**
- **fix(oversight): more number format tweaks**
- **fix(oversight): guard against empty iterator**
- **refactor(sankey): use new …
=> Oversight/Sankey: Classify Acquisition Sources

tools/oversight/elements/link-facet.js, tools/oversight/explorer.html, tools/oversight/rum-slicer.css
Some requested backports:
- remove pagespeed icon
- never show protocol and hostname in URLs
=> feat(rum-oversight): cleanup backport

tools/rum/explorer.html, tools/rum/slicer.js
Conversions was broken, always 100%. Not fully sure but I think it should be `clicks` / `pageviews`.
Test page: https://fix-conversions--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.adobe.com&filter=&view=week&domainkey=incognito
=> fix(rum-explorer): compute conversions

tools/oversight/cruncher.js, tools/oversight/elements/list-facet.js, tools/oversight/slicer.js, tools/rum/cruncher.js, tools/rum/elements/list-facet.js, tools/rum/slicer.js
In the `filter` input, type `click` and then `clicke`, then `clicked`... The UI start being unresponsive (or at least slower), facets are not emptied and `click` is still the value highlighted.
This PR addresses the 2 aspects:
- make sure we do not recompute the `filtered` data chunks (not computed !== length === 0)
- reset the list-facet if no facet entry
- bonus: fix the filtertext concat (first checkpoint is part of the url)
Applied fix to `rum` and `oversight`.
Test: 
- https://unmatched-filter--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.adobe.com&filter=&view=week&domainkey=incognito
- https://unmatched-filter--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=www.adobe.com&filter=&view=week&domainkey=incognito
=> fix: un-matched filter

tools/oversight/elements/url-selector.js, tools/rum/elements/url-selector.js
`aem.live:all` is a special org domain but it cannot be entered via the UI.
Test: https://allow-special-domains--helix-website--adobe.hlx.live/tools/rum/explorer.html?domain=aem.live%3Aall&view=month&domainkey=
=> fix(rum-explorer): allow special domains (not url)

tools/oversight/rum-slicer.css, tools/rum/rum-slicer.css
- url selector to full width (`experienceleague.adobe.com` does not fit the box at the moment)
- reshape the copy icon
- 
Test: : https://ui-tweaks--helix-website--adobe.hlx.live/tools/rum/explorer.html?domain=experienceleague.adobe.com&view=month&domainkey=
=> feat(rum-explorer): ui tweaks

tools/rum/elements/file-facet.js, tools/rum/elements/thumbnail-facet.js, tools/rum/explorer.html, tools/rum/rum-slicer.css, tools/rum/slicer.js
`media_x` is rendered relative to the current page, which means the same image might be rendered with different paths. Those new to be grouped together in the Media Target facet.
Showing the thumbnail then becomes problematic (one of those should be shown or root one cannot be used but it does not work in all the cases). More generally, thumbnails are useless, rendered stretched and overload the UI (might also lead to be blocked by remote host). This PR adds a File Facet to only show the filename.
Test: https://media-facet--helix-website--adobe.hlx.live/tools/rum/explorer.html?domain=www.bamboohr.com&view=month&domainkey=
=> fix(rum-explorer): media are the same

tools/rum/cruncher.js, tools/rum/explorer.html, tools/rum/slicer.js, tools/rum/utils.js
Adds new Host Type facet.
Test:
- Facet is enabled: https://host-type--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=aem.live:all&filter=&view=week&domainkey=
- Facet is disabled: https://host-type--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=aem.live:all&filter=&view=week&domainkey=
=> feat: host type facet

tools/oversight/cruncher.js, tools/oversight/explorer.html, tools/oversight/slicer.js, tools/oversight/utils.js
Oversight version of #621.
@trieloff No need for extra capability: either hostType is provided for the `aem.live:all` domain or it is not, i.e. no entry at all, facet is then not visible.
Test:
Facet is enabled: https://host-type-lab--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=aem.live:all&filter=&view=week&domainkey=
Facet is disabled: https://host-type-lab--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=aem.live:all&filter=&view=week&domainkey=
=> feat(rum-oversight): host type facet

tools/oversight/cruncher.js
Save a loop in the applyFilter method of cruncher (as applyFilter is getting called a lot).
The applyFilter method is called a lot and it seems to iterate over a result list to see if every value is true which it looks like could be done directly.
Speed-up the applyFilter method
Looking at the ui rendering speed timing in the console at:
https://filter--helix-website--karlpauls.hlx.page/tools/oversight/explorer.html?domain=aem.live&domainkey=
=> feat(rum-oversight): improve applyFilter

tools/oversight/slicer.js
Currently, the loadData method is calling draw at the end. This causes some duplicated call to the draw method of the chart - it doesn't really seem to be a performance problem (nor cause other issues) but it seems it would make some sense to move the draw call out of loadData and invoke it explicitly when needed. 
Test: https://slicerdraw--helix-website--karlpauls.hlx.page/tools/oversight/explorer.html?domain=aem.live&domainkey=
=> feat(rum-oversight): split draw from loadData

tools/oversight/consent.js
The matching in consent maps over all possibilities. Replacing it with find can shortcut the evaluation as only one match is required.
Replace the map in consent with a find and delay the actual look up of the target. 
Trying to improve the speed of consent matching.
Looking at the ui rendering speed in the console at 
https://consentmatching--helix-website--karlpauls.hlx.page/tools/oversight/explorer.html?domain=aem.live&domainkey=
=> feat(rum-oversight): improve matching in consent

tools/oversight/charts/skyline.js
In the skyline chart, the aggregates result gets mapped several times. 
This patch proposes to only loop one time using a reduce.
Speed up the rendering in skyline chart.
Looking at the ui rendering speed in the console at
https://skylinereduce--helix-website--karlpauls.hlx.page/tools/oversight/explorer.html?domain=aem.live&domainkey=
=> feat(rum-oversight): improve reduce in skyline

tools/oversight/utils.js
The scoreCWV method is using a loop that can be unrolled to improve performance (as it doesn't gc as much)
Since the method gets very hot, it seems to produce less gc if it doesn't keep creating a list for the values (the code looks a little more verbose).
Speedup the scoreCWV method
Looking at the ui rendering speed in the console at
https://utilunroll--helix-website--karlpauls.hlx.page/tools/oversight/explorer.html?domain=aem.live&domainkey=
=> feat(rum-oversight): unroll scoreCWV loop in util

tools/oversight/acquisition.js
Use find instead of reduce in acquisition to shortcut evaluation.
It seems like we can use find instead of reduce in acquisitions to shortcut the search.
Speedup the acquisition evaluation.
Looking at the ui rendering speed in the console at 
https://acquisitionreduce--helix-website--karlpauls.hlx.page/tools/oversight/explorer.html?domain=aem.live&domainkey=
=> feat(rum-oversight): use find instead of reduce in acquisition

tools/rum/elements/url-selector.js
https://www.aem.live/tools/rum/explorer.html?domain=test.com%3Aall
vs.
https://rum-icon-fix--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=test.com%3Aall
=> chore(rum): display fix for favicon for aggregates with `:`

tools/oversight/cruncher.js, tools/oversight/elements/list-facet.js, tools/oversight/rum-slicer.css, tools/oversight/slicer.js, tools/oversight/test/cruncher.test.js, tools/oversight/utils.js
as of now, this PR does not come with a UI, and it is only limited to the URL facet. You can try it
by appending `&url!=https://examplehost.com/examplepath` – this will then exclude that particular URL
from all results shown in the UI. I haven't tried what happens when you combine this with the opposite,
but my expectation is that you end up with an empty set, as different facets are combined with AND.
The PR also adds a `never` combiner option to factets, enforcing that every single facet value must
not satisfy the facet conditions.
=> Support Negative URL Facet

tools/oversight/rum-slicer.css
As of 2024, CWV readings with iOS user agents are coming from non-iOS browsers
that falsify their user agent string. This can include Chrome when using devtools
and simulating a mobile viewport. Apple does not allow custom rendering engines
in most of the world, and in the EU, where it does allow custom rendering engines,
no browser vendor ships a browser with a non-WebKit engine, so that all actual
iOS browsers are just WebKit in disguise. Webkit does not implement key APIs required
for measurement of Core Web Vitals, effectively rendering all CWVs readings that
claim to apply to iOS suspect.
This PR addresses this by reducing the visual contrast of the CWV pills for the
user agent iOS only.
=> feat(oversight): show that iOS CWVs are fake

tools/oversight/elements/list-facet.js, tools/oversight/slicer.js, tools/oversight/test/utils.test.js, tools/oversight/utils.js
This change will make sure that after clicking "more" in the facet ui, and selecting a value, the facet will remember how far it got expanded. This also prevents obscure facet values from becoming invisible after selecting them.
=> Preserve facet expansion

blocks/feed/feed.css, blocks/feed/feed.js
This PR addresses limiting the number of lines visible for description of each discord event in Feed Block
Fix for #646 
Better user experience
(Limiting visible content to 5 lines)
https://main--helix-website--adobe.aem.page/community
vs
https://issue-646--helix-website--adobe.aem.page/community
=> Limit visible lines for description in Feed Block

tools/rum/elements/link-facet.js, tools/rum/elements/list-facet.js
2 changes:
-  allow to open explorer for domains (org / `:all` case)
- limit the click handler to the checkbox (super annoying that you cannot copy/paste urls)
Test: https://domain-nav--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=adobe.com%3Aall&filter=&view=month
=> feat(rum-explorer): domain navigation for orgs

tools/rum/charts/skyline.js, tools/rum/cruncher.js, tools/rum/slicer.js, tools/rum/utils.js
Backport performance tweaks from oversight to rum:
- c0766085c23ac78d29efdfa03405d19c730be677
- 492a457274f3000925f8ef0d9f1ea5370ad6d5e1
- 69a4087cd2f1c58f91659156f039c7c4a9ffd70e
- 003a613dd9ec005f40acfc1a3f768a1681cbd519
- 6faf5cc5e0ade99c8707e9947b933dac93fd19d4
We merged a couple of performance tweaks to oversight. This is the subsection of these that apply to the rum explorer.
Looking at the ui rendering speed in the console at: https://main--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.bulk.com&domainkey=
=> feat(rum-explorer): perf tweaks (backport from oversight)

tools/oversight/elements/url-selector.js, tools/rum/elements/url-selector.js
https://datalist--helix-website--adobe.aem.page/tools/rum/explorer.html
https://datalist--helix-website--adobe.aem.page/tools/oversight/explorer.html
=> feat: get domain suggestions for url input

tools/oversight/elements/url-selector.js, tools/rum/elements/url-selector.js
- load domain suggestions lazily on mouseover
- don't load suggestions when in incognito mode
https://suggestion-tweaks2--helix-website--adobe.aem.live/tools/rum/explorer.html
https://suggestion-tweaks2--helix-website--adobe.aem.live/tools/oversight/explorer.html
=> suggestion tweaks

tools/rum/cruncher.js, tools/rum/test/cruncher.test.js
While working on a conversion filter, I was surprised by the results: they had a tendency to be really good while I was expecting low results. I realised that if one of the facet in the filter is not defined on the DataChunks, it is ignored. This leads to super good results while it is just a misconfiguration of the filter. As a consumer of the cruncher, I did not know I was using the filter incorrectly, especially when you start combining multiple of them and you get already a subset of the results, it is impossible to know one is invalid and just ignored.
I think it makes more sense to return no result (and log an error) if someone is trying to filter on something which is not defined. This is much more intuitive. 
One of the existing test `DataChunk.filter(userAgent)` has the problem: …
=> fix(rum-explorer): unknown filter should return empty set

tools/rum/elements/daterange-picker.js
Depending on timezone, current time might lead to one day before or one day after the from / to selection. This leads to strange behaviours of the range picker. See recording:
https://github.com/user-attachments/assets/f97a8c19-a114-469a-98ba-a76c8825966b
Test: https://timezone-issue--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=blog.adobe.com&filter=&view=custom&startDate=2024-10-07&endDate=2024-10-08&userAgent=desktop&checkpoint=click&domainkey=incognito
Test requires to change the computer timezone.
=> fix: wrong date depending on timezone

404.html, scripts/redirects.js, tests/scripts/redirects.test.js
The tests requires a change to `404.html` which only applies to `main`, therefore I've written unit
tests.
Our example `smart-redirects.json` sheet has a redirect pattern rule from `/documentation/*` to `/docs/*`
- **feat(404): create error page from boilerplate**
- **feat(404): apply smart redirects, but don't send 404 checkpoint if a redirect has been found**
- **test(smartredirects): add tests for the meat of the code**
=> Smart Redirects

tools/oversight/elements/link-facet.js, tools/oversight/elements/list-facet.js
When filtering out and only one url remains in the URL facet, the url is shown as `.../`. Expected: at least see the url path.
Before: https://www.aem.live/tools/oversight/explorer.html?domain=www.adobe.com&filter=%2Fproducts%2Fcatalog.html&view=month&=performance&domainkey=incognito&conversion.checkpoint=click
After: https://solo-url--helix-website--adobe.aem.page/tools/oversight/explorer.html?domain=www.adobe.com&filter=%2Fproducts%2Fcatalog.html&view=month&=performance&domainkey=incognito&conversion.checkpoint=click
=> feat(rum-oversight): do not collapse solo entry

tools/oversight/slicer.js, tools/rum/slicer.js
In the case of an org, the bundles contain only a subset of the checkpoints, not including `enter`, i.e. `visit` is always 0. This is not intuitive. While we can work on a better UX, a quick fix is to show `N/A`.
=> feat(rum): show N/A if no visit data is provided (org case)

tools/oversight/explorer.html, tools/rum/explorer.html
Allow to see the `source` of the `missingresource` checkpoint
=> feat(rum): allow to see source of missingresource

tools/oversight/slicer.js, tools/rum/slicer.js
When selecting a date range, the last day does not contain data.
Text: https://end-of-date--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.maidenform.com&filter=&view=custom&startDate=2024-11-12&endDate=2024-11-18&domainkey=
=> feat: include end of the last day of the selected period

blocks/author-box/author-box.js
see https://author-link--helix-website--adobe.aem.page/blog/sidekick-v7
@asthabh23 not sure why you used a click handler in the first place, but this PR replaces it with native links
=> fix(author-box): don't use click handler for links

.github/workflows/update-importmaps.yml, .renovaterc.json, tools/imports.sh
=> chore(renovate): use nicer branch names for renovate

helix-query.yaml
This PR adds publication-date to helix-query.yaml to index this field for blog posts
#731 
This will be helpful for filtering blogs on blog listing page
https://main--helix-website--adobe.aem.page/blog/aem-live-at-dev-live
vs
https://issue-731--helix-website--adobe.aem.page/blog/aem-live-at-dev-live
=> chore: add publication-date to helix-query.yaml

.github/workflows/log-publish.yml
This PR adds webhook-type for slack-github-action which currently fails sending notification on slack channel when docs are published
#733 
This was working before a dependency update happened 2 weeks back, this PR will fix the issue.
=> Slack notification should be sent when docs are published

tools/oversight/charts/skyline.js, tools/rum/charts/skyline.js
Open https://www.aem.live/tools/rum/explorer.html?domain=www.ups.com&view=month&domainkey=incognito
Check the Y axis labels of the chart: CLS is missing. It is not the case for all charts (works for https://www.aem.live/tools/rum/explorer.html?domain=blog.adobe.com&view=month&domainkey=incognito
Test:
- https://missing-label--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.ups.com&view=month&domainkey=incognito
- https://missing-label--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=blog.adobe.com&view=month&domainkey=incognito
Just simplified the logic...
=> fix: simplify Y labelling

tools/oversight/slicer.js, tools/rum/slicer.js
fixes #747 
Try the same steps with this URL (replace `incognito` with the correct domain key)
https://deselect-checkpoint--helix-website--vdua.aem.live/tools/oversight/explorer.html?domain=business.adobe.com&filter=&view=month&=performance&checkpoint=click&click.source=button.con-button&domainkey=incognito&conversion.checkpoint=click
We remove the source/target filters from the state if the checkpoint is not present in the filter.
=> bug: deselecting a checkpoint breaks the dashboard in certain scenarios

styles/styles.css
There is a margin issue at the top of most pages and the breadcrumb that was introduced by accident...
see: https://github.com/adobe/helix-website/commit/5e0e854282c16d49d90eb05307df1bfa0a5e9524#diff-37f6471b306924bbb531d040e7ab55df5f83511246a411d22947462323516afaR1932-R1936
https://main--helix-website--adobe.aem.live/
https://main--helix-website--adobe.aem.live/docs/
vs.
https://fix-margin--helix-website--adobe.aem.live/
https://fix-margin--helix-website--adobe.aem.live/docs/
=> fix: broken top margins

tools/oversight/elements/list-facet.js, tools/oversight/explorer.html, tools/oversight/flow.html, tools/oversight/list.html, tools/oversight/rum-slicer.css, tools/oversight/share.html, tools/oversight/single.html, tools/rum/elements/list-facet.js, tools/rum/explorer.html, tools/rum/rum-slicer.css
This PR adds help icon to the facets on explorer and oversight and adds link to the respective sections of official documentation.
#755 
For easy understanding of the use of different facets on RUM Dashboard
Explorer:
https://main--helix-website--adobe.aem.page/tools/rum/explorer.html?domain=emigrationbrewing.com&filter=&view=month&metrics=all&domainkey=open
vs
https://facets-help--helix-website--adobe.aem.page/tools/rum/explorer.html?domain=emigrationbrewing.com&filter=&view=month&metrics=all&domainkey=open
Oversight:
https://main--helix-website--adobe.aem.page/tools/oversight/explorer.html?domain=emigrationbrewing.com&filter=&view=month&metrics=all&domainkey=open
vs
https://facets-help--helix-website--adobe.aem.page/tools/oversight/explorer.html?domain=emigrationbrewing.com&filter=&view= …
=> feat: Help for facets

blocks/author-box/author-box.css, blocks/author-box/author-box.js, scripts/scripts.js
This PR covers:
- Adding support for multiple authors in author-box block for aem.live/blog
- Updating navigation to blog section from breadcrumb
- It also slightly updates the styling for author-box for single author.
#773 
Currently author-box supports only one author, this PR enhances the block to support multiple authors. This will be useful for future blogs too where more than one author contributes to the blog
Multiple authors:
https://main--helix-website--adobe.aem.page/drafts/asthabharga/blog
vs
https://issue-773--helix-website--adobe.aem.page/drafts/asthabharga/blog
Single author:
https://main--helix-website--adobe.aem.page/blog/aem-live-at-dev-live
vs
https://issue-773--helix-website--adobe.aem.page/blog/aem-live-at-dev-live
=> Multiple author support in author-box

blocks/cards/cards.css, blocks/cards/cards.js
- Adds baseline alternate definition for upper-corner triangle
- Adds with 3 color options (red for deprecated, pink-ish for early access, grey for removed). 
- Fixes a minor issue with the Cards JS where adding card block options applies baseline button styles to contained links in addition to 'link-highlight-colorful-effect-hover-wrapper'.  This is 
https://github.com/adobe/helix-website/issues/782
Before: https://main--helix-website--adobe.aem.page/drafts/brwarner/lifecycle
After: https://coloredcardcorners--helix-website--adobe.aem.page/drafts/brwarner/lifecycle
=> Added block option styles to Cards block

blocks/faq/faq.css, blocks/faq/faq.js
Add opt-in category labels and allow filtering. If a sheet has a `Category` column with values in it, the FAQ block will add category tags to those entries, and allow the user to filter for certain categories.
Before: https://main--helix-website--adobe.aem.page/drafts/rofe/cat
After: https://faq-cats--helix-website--adobe.aem.page/drafts/rofe/cat?filter=Lorem
=> FAQ: add optional categories and filters

blocks/feed/feed.css, blocks/feed/feed.js
Treating images as <img> tags than <a>
fix: #787 
To display images
Testing manually
Before 
After 
Before: https://main--helix-website--adobe.aem.live/blog
After: https://blog-feed-images--helix-website--adobe.aem.live/blog
=> chore: loading images as img tag rather than links in ./blog

styles/styles.css
Issue: Go to the FAQ page and search for 'blocks'. It looks weird compared to the rest of the pages on the site
Before: https://main--helix-website--adobe.aem.page/docs/faq
After: https://faq-search-fix--helix-website--adobe.aem.page/docs/faq
=> fix: faq theme search results styling

blocks/cards/cards.css
3 column card layout can break between 900 and 1200px:
Before: https://main--helix-website--adobe.aem.page/docs/deprecation
After: https://card-layout-fix--helix-website--adobe.aem.page/docs/deprecation
=> fix: card layout between mobile and desktop

blocks/side-navigation/side-navigation.js
unpublished resource 404ing on when using the `side-navigation` block search feature.
before: https://www.aem.live/developer/tutorial
after: https://side-nav-src--helix-website--adobe.aem.page/developer/tutorial
=> fix: published doc search source

blocks/feed/feed.js
Continuation of #813 
https://main--helix-website--adobe.aem.live/blog
vs
https://blog-order--helix-website--adobe.aem.live/blog
=> fix: repetition of first blog in blog cards

tools/oversight/elements/number-format.js
When adding/removing facets in the sidebar, the browser frequently becomes hung. Was able to trace it to the mutation observer, which seems to infinite loop. Basically, it seems like even though we are calling disconnect, it doesn't actually get disconnected immediately. Fixed by using a span inside the element for storing the formatted value. When the element is updated externally, that happens with a simple `.textConent = ${value}`, so this should be safe and works per my testing.
I considered just using a set timeout after disconnecting, which works too. Not sure which approach I like better, so open to thoughts here.
https://cq-dev.slack.com/archives/C07198KKQ07/p1744313769838479
test urls, add domain key and add/remove facets vis sidebar to see the difference.
Before: …
=> fix: avoid mutation observer infinite looping in rum oversight

scripts/scripts.js
Since the refactoring of the FAQ page, we no longer have anchor links on the headings.
https://main--helix-website--adobe.aem.page/docs/faq
vs
https://faq-headings--helix-website--adobe.aem.page/docs/faq
=> fix: bring back faq heading anchors

blocks/feed/feed.js
This PR fixes the order of blog posts on https://www.aem.live/blog
#827 
Currently the order seems to be missing 1-2 blogs. Fix needed to rightly display blogs in descending order of publication date.
The blogs now appear in the right expected order.
https://main--helix-website--adobe.aem.page/blog
vs
https://issue-827--helix-website--adobe.aem.page/blog
=> fix: order of blog posts

blocks/columns/columns.css, blocks/columns/columns.js
Changed two-column view to use `fr` rather than %. Also if the column only contains one child (that is a text node), wrap it in a `p` tag to get correct formatting.
#852 
Fix the visual
Visually validated the changes on the problem page.
Test URL: https://bug-columns-img-width--helix-website--adobe.aem.live/docs/authentication-setup-authoring
=> Column Block - Fix image & Text formatting.

blocks/labs/labs.js
Before: https://main--helix-website--adobe.aem.live/developer/content-fragment-overlay
After: https://labs-teams--helix-website--adobe.aem.live/developer/content-fragment-overlay
=> chore: mention teams in the default EAT banner message

blocks/ue-trial/ue-trial.js
UE Trial form submits wrong default template
Updated the radio button handling to ensure checked attributes are only set when necessary.
fixes #900 
Test URL: https://fix-template-selection--helix-website--adobe.aem.live/developer/ue-trial
=> fix: streamline template selection logic in ue trial

AGENTS.md
- Add anchored links to AEM Development Collaboration and Good Practices:
- CSS (#css) and JavaScript (#javascript)
- HTML head guidance (#head)
- 3rd-party library loading (#loading-3rd-party-libraries)
- Add Block Development reference to align block creation with best practices
- Fix typos: “html”→“HTML”, “sturcture”→“structure”; correct environments parenthesis
- No functional code changes
Refs:
- https://www.aem.live/docs/dev-collab-and-good-practices
- https://www.aem.live/docs/dev-collab-and-good-practices#css
- https://www.aem.live/docs/dev-collab-and-good-practices#javascript
- https://www.aem.live/docs/dev-collab-and-good-practices#head
- https://www.aem.live/docs/dev-collab-and-good-practices#loading-3rd-party-libraries
=> docs(agents.md): referencing aem best practices and fix typos

tools/rum/utils.js
Root issue this is intended to fix is that billions were displayed as `#.##g` instead of `#.##b`. adjust unit suffixes for billion and quadrillion to use b and q respectively instead of g and p (e.g common English units rather than SI units).
#916
https://num-format--helix-website--adobe.aem.live/tools/rum/explorer.html?domain=www.ups.com&filter=&view=year&url=https%3A%2F%2Fwww.ups.com%2Ftrack&domainkey=
=> refactor(rum): improve `toHumanReadable` function for better number formatting

tools/oversight/slicer.js
see https://negate-url--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=emigrationbrewing.com&filter=&view=month&=performance&url%21=https%3A%2F%2Femigrationbrewing.com%2Fdinner&domainkey=open&conversion.checkpoint=click
=> fix(oversight): allow negation of url facet, despite clustering

tools/oversight/slicer.js
This PR fixes unknown checkpoint warning in OpTel dashboard browser console. This fix reduces the overall page load time for the dashboard.
#931 
Observed delay in dashboard load time.
Warning no longer appears
https://main--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=emigrationbrewing.com&filter=&view=month&=performance&domainkey=open
vs
https://issue-931--helix-website--adobe.aem.live/tools/oversight/explorer.html?domain=emigrationbrewing.com&filter=&view=month&=performance&domainkey=open
=> fix(oversight): unknown checkpoint warning in console
